# Generated by Django 4.2.1 on 2023-05-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account',
            new_name='user',
        ),
    ]
