# Generated by Django 4.2.1 on 2023-05-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_account_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='account',
            new_name='user',
        ),
    ]
