# Generated by Django 4.2.1 on 2023-05-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_account_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='account',
            new_name='user',
        ),
    ]
