# Generated by Django 4.2.1 on 2023-05-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_address_line1_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
